language: python

python:
  - 2.7

install:
  - pip install django flake8

before_script:
  - python manage.py migrate

script:
  - python manage.py test
  - flake8 --exclude polls/migrations/,manage.py .

# before_deploy:
#   - heroku buildpacks:set -a gcs01-gabrielsclimaco-travis heroku/python

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  buildpack: python
  app: gcs01-gabrielsclimaco-travis
