language: python

python:
  - 2.7

install:
  - pip install django flake8

before_script:
  - python django-basic/manage.py migrate

script:
  - python django-basic/manage.py test
  - flake8 --exclude django-basic/polls/migrations/,manage.py .

before_deploy:
  - docker build -t registry.heroku.com/gcs01-gabrielsclimaco-travis/web .
  - docker push registry.heroku.com/gcs01-gabrielsclimaco-travis/web

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: gcs01-gabrielsclimaco-travis
  run: "docker exec registry.heroku.com/gcs01-gabrielsclimaco-travis python manage.py runserver 0:8000"
