language: python

python:
  - 2.6
  - 2.7

install:
  - pip install django flake8

before_script:
  - python django-basic/manage.py migrate

script:
  - python django-basic/manage.py test
  - flake8 --exclude django-basic/polls/migrations/,manage.py .
